// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: css_service.proto

package cssservicepb

import (
	css "github.com/accretional/proto-css/proto/pb/css"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stylesheet to render. Any css.* subtree is reachable from here.
	Sheet         *css.CssStyleSheet `protobuf:"bytes,1,opt,name=sheet,proto3" json:"sheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_css_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_css_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_css_service_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetSheet() *css.CssStyleSheet {
	if x != nil {
		return x.Sheet
	}
	return nil
}

type RenderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rendered CSS text.
	Css           string `protobuf:"bytes,1,opt,name=css,proto3" json:"css,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_css_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_css_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_css_service_proto_rawDescGZIP(), []int{1}
}

func (x *RenderResponse) GetCss() string {
	if x != nil {
		return x.Css
	}
	return ""
}

type RenderChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A slice of the rendered CSS text. Concatenate chunks in arrival order.
	Css           string `protobuf:"bytes,1,opt,name=css,proto3" json:"css,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderChunk) Reset() {
	*x = RenderChunk{}
	mi := &file_css_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChunk) ProtoMessage() {}

func (x *RenderChunk) ProtoReflect() protoreflect.Message {
	mi := &file_css_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChunk.ProtoReflect.Descriptor instead.
func (*RenderChunk) Descriptor() ([]byte, []int) {
	return file_css_service_proto_rawDescGZIP(), []int{2}
}

func (x *RenderChunk) GetCss() string {
	if x != nil {
		return x.Css
	}
	return ""
}

type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CSS text to parse.
	Css           string `protobuf:"bytes,1,opt,name=css,proto3" json:"css,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_css_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_css_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_css_service_proto_rawDescGZIP(), []int{3}
}

func (x *ParseRequest) GetCss() string {
	if x != nil {
		return x.Css
	}
	return ""
}

type ParseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parsed stylesheet.
	Sheet         *css.CssStyleSheet `protobuf:"bytes,1,opt,name=sheet,proto3" json:"sheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_css_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_css_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_css_service_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResponse) GetSheet() *css.CssStyleSheet {
	if x != nil {
		return x.Sheet
	}
	return nil
}

var File_css_service_proto protoreflect.FileDescriptor

const file_css_service_proto_rawDesc = "" +
	"\n" +
	"\x11css_service.proto\x12\x03css\x1a\tcss.proto\"9\n" +
	"\rRenderRequest\x12(\n" +
	"\x05sheet\x18\x01 \x01(\v2\x12.css.CssStyleSheetR\x05sheet\"\"\n" +
	"\x0eRenderResponse\x12\x10\n" +
	"\x03css\x18\x01 \x01(\tR\x03css\"\x1f\n" +
	"\vRenderChunk\x12\x10\n" +
	"\x03css\x18\x01 \x01(\tR\x03css\" \n" +
	"\fParseRequest\x12\x10\n" +
	"\x03css\x18\x01 \x01(\tR\x03css\"9\n" +
	"\rParseResponse\x12(\n" +
	"\x05sheet\x18\x01 \x01(\v2\x12.css.CssStyleSheetR\x05sheet2\xa7\x01\n" +
	"\n" +
	"CssService\x121\n" +
	"\x06Render\x12\x12.css.RenderRequest\x1a\x13.css.RenderResponse\x126\n" +
	"\fRenderStream\x12\x12.css.RenderRequest\x1a\x10.css.RenderChunk0\x01\x12.\n" +
	"\x05Parse\x12\x11.css.ParseRequest\x1a\x12.css.ParseResponseBCZAgithub.com/accretional/proto-css/proto/pb/cssservice;cssservicepbb\x06proto3"

var (
	file_css_service_proto_rawDescOnce sync.Once
	file_css_service_proto_rawDescData []byte
)

func file_css_service_proto_rawDescGZIP() []byte {
	file_css_service_proto_rawDescOnce.Do(func() {
		file_css_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_css_service_proto_rawDesc), len(file_css_service_proto_rawDesc)))
	})
	return file_css_service_proto_rawDescData
}

var file_css_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_css_service_proto_goTypes = []any{
	(*RenderRequest)(nil),     // 0: css.RenderRequest
	(*RenderResponse)(nil),    // 1: css.RenderResponse
	(*RenderChunk)(nil),       // 2: css.RenderChunk
	(*ParseRequest)(nil),      // 3: css.ParseRequest
	(*ParseResponse)(nil),     // 4: css.ParseResponse
	(*css.CssStyleSheet)(nil), // 5: css.CssStyleSheet
}
var file_css_service_proto_depIdxs = []int32{
	5, // 0: css.RenderRequest.sheet:type_name -> css.CssStyleSheet
	5, // 1: css.ParseResponse.sheet:type_name -> css.CssStyleSheet
	0, // 2: css.CssService.Render:input_type -> css.RenderRequest
	0, // 3: css.CssService.RenderStream:input_type -> css.RenderRequest
	3, // 4: css.CssService.Parse:input_type -> css.ParseRequest
	1, // 5: css.CssService.Render:output_type -> css.RenderResponse
	2, // 6: css.CssService.RenderStream:output_type -> css.RenderChunk
	4, // 7: css.CssService.Parse:output_type -> css.ParseResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_css_service_proto_init() }
func file_css_service_proto_init() {
	if File_css_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_css_service_proto_rawDesc), len(file_css_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_css_service_proto_goTypes,
		DependencyIndexes: file_css_service_proto_depIdxs,
		MessageInfos:      file_css_service_proto_msgTypes,
	}.Build()
	File_css_service_proto = out.File
	file_css_service_proto_goTypes = nil
	file_css_service_proto_depIdxs = nil
}
