// Code generated by gluon servicegen (run via genproto). DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: css_service.proto

package cssservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CssService_Render_FullMethodName       = "/css.CssService/Render"
	CssService_RenderStream_FullMethodName = "/css.CssService/RenderStream"
	CssService_Parse_FullMethodName        = "/css.CssService/Parse"
)

// CssServiceClient is the client API for CssService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CssService renders typed CssStyleSheet messages to CSS text and parses CSS text
// back. CssStyleSheet is the grammar's start symbol — every css.* message is
// reachable from it — so both directions are rooted there. Both directions are
// pure reflection over the grammar-derived schema in css.proto plus the generated
// tables; the gluon codec does all parsing and rendering, so the implementing
// server carries no per-rule logic.
type CssServiceClient interface {
	// Render serializes the request's CssStyleSheet into CSS text.
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
	// RenderStream serializes the request's CssStyleSheet and streams the CSS text
	// in chunks. The concatenation of all chunks equals Render's `css`.
	RenderStream(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RenderChunk], error)
	// Parse parses CSS text into a typed CssStyleSheet.
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type cssServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCssServiceClient(cc grpc.ClientConnInterface) CssServiceClient {
	return &cssServiceClient{cc}
}

func (c *cssServiceClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, CssService_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cssServiceClient) RenderStream(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RenderChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CssService_ServiceDesc.Streams[0], CssService_RenderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RenderRequest, RenderChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CssService_RenderStreamClient = grpc.ServerStreamingClient[RenderChunk]

func (c *cssServiceClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, CssService_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CssServiceServer is the server API for CssService service.
// All implementations must embed UnimplementedCssServiceServer
// for forward compatibility.
//
// CssService renders typed CssStyleSheet messages to CSS text and parses CSS text
// back. CssStyleSheet is the grammar's start symbol — every css.* message is
// reachable from it — so both directions are rooted there. Both directions are
// pure reflection over the grammar-derived schema in css.proto plus the generated
// tables; the gluon codec does all parsing and rendering, so the implementing
// server carries no per-rule logic.
type CssServiceServer interface {
	// Render serializes the request's CssStyleSheet into CSS text.
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	// RenderStream serializes the request's CssStyleSheet and streams the CSS text
	// in chunks. The concatenation of all chunks equals Render's `css`.
	RenderStream(*RenderRequest, grpc.ServerStreamingServer[RenderChunk]) error
	// Parse parses CSS text into a typed CssStyleSheet.
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedCssServiceServer()
}

// UnimplementedCssServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCssServiceServer struct{}

func (UnimplementedCssServiceServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedCssServiceServer) RenderStream(*RenderRequest, grpc.ServerStreamingServer[RenderChunk]) error {
	return status.Error(codes.Unimplemented, "method RenderStream not implemented")
}
func (UnimplementedCssServiceServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedCssServiceServer) mustEmbedUnimplementedCssServiceServer() {}
func (UnimplementedCssServiceServer) testEmbeddedByValue()                    {}

// UnsafeCssServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CssServiceServer will
// result in compilation errors.
type UnsafeCssServiceServer interface {
	mustEmbedUnimplementedCssServiceServer()
}

func RegisterCssServiceServer(s grpc.ServiceRegistrar, srv CssServiceServer) {
	// If the following call panics, it indicates UnimplementedCssServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CssService_ServiceDesc, srv)
}

func _CssService_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CssServiceServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CssService_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CssServiceServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CssService_RenderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RenderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CssServiceServer).RenderStream(m, &grpc.GenericServerStream[RenderRequest, RenderChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CssService_RenderStreamServer = grpc.ServerStreamingServer[RenderChunk]

func _CssService_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CssServiceServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CssService_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CssServiceServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CssService_ServiceDesc is the grpc.ServiceDesc for CssService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CssService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "css.CssService",
	HandlerType: (*CssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _CssService_Render_Handler,
		},
		{
			MethodName: "Parse",
			Handler:    _CssService_Parse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RenderStream",
			Handler:       _CssService_RenderStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "css_service.proto",
}
