#!/usr/bin/env python3
"""showcase.py — regenerate the curated showcase in README.md from showcase.json.

`showcase.json` is the multimodal-review handpick: for each property, the single
most visually striking value (its index in generated/values.json), the value
string, and a 4–5 star score. This script resolves each pick to its screenshot
under screenshots/<prop>/<NN>-*.* (preferring the animated GIF for temporal
properties), groups by family, and rewrites the table between the
<!-- SHOWCASE:START --> / <!-- SHOWCASE:END --> markers in README.md.

  python3 showcase.py
"""
import os, json, glob

HERE = os.path.dirname(os.path.abspath(__file__))
SHOTS = os.path.join(HERE, "screenshots")
README = os.path.join(HERE, "README.md")
PICKS = os.path.join(HERE, "showcase.json")
THUMB = 260
PER_FAMILY = 8   # cap so one family (e.g. the corner-* shapes) can't dominate

# family id (from the generated manifest) -> display title, in showcase order
FAMILIES = [
    ("effects",       "Filters, blending & shadows"),
    ("clip-mask",     "Masking & clipping"),
    ("backgrounds",   "Backgrounds & gradients"),
    ("color",         "Colour"),
    ("borders",       "Borders, outlines & corners"),
    ("transforms",    "Transforms"),
    ("object-image",  "Object & image"),
    ("svg",           "SVG paint"),
    ("shapes",        "Shapes"),
    ("typography",    "Typography"),
    ("text-styling",  "Text styling & decoration"),
    ("writing-mode",  "Writing mode & direction"),
    ("line-spacing",  "Line & inline spacing"),
    ("lists",         "Lists"),
    ("columns",       "Multi-column"),
    ("flexbox",       "Flexbox"),
    ("grid",          "Grid"),
    ("sizing",        "Sizing"),
    ("positioning",   "Positioning & display"),
    ("box-display",   "Box model & display"),
    ("containment",   "Containment"),
    ("anchor",        "Anchor positioning"),
    ("offset",        "Motion path"),
    ("transitions",   "Transitions (animated)"),
    ("animations",    "Animation (animated)"),
    ("interactivity", "Interaction"),
    ("breaks",        "Fragmentation"),
    ("tables",        "Tables"),
    ("misc",          "Misc"),
]
TITLES = dict(FAMILIES)
ORDER = {fam: i for i, (fam, _) in enumerate(FAMILIES)}


def shot(prop, index):
    """Path (relative to chrome-testing/) of the screenshot for prop@index — the
    animated GIF if there is one, else the still PNG."""
    pre = "%02d-" % index
    for ext in ("gif", "png"):
        m = sorted(glob.glob(os.path.join(SHOTS, prop, pre + "*." + ext)))
        if m:
            return os.path.relpath(m[0], HERE)
    m = sorted(glob.glob(os.path.join(SHOTS, prop, pre + "*")))
    return os.path.relpath(m[0], HERE) if m else None


def esc(s):
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render(picks):
    groups = {}
    for p in picks:
        groups.setdefault(p["family"], []).append(p)
    out = ["<!-- SHOWCASE:START -->",
           "*Auto-generated by `showcase.py` from `showcase.json` — the multimodal-review "
           "handpick: the single most striking value of each property. "
           "Animated properties show their GIF.*", ""]
    shown = 0
    for fam in sorted(groups, key=lambda f: ORDER.get(f, 999)):
        rows = sorted(groups[fam], key=lambda p: (-p["score"], p["prop"]))[:PER_FAMILY]
        rows = [(p, shot(p["prop"], p["index"])) for p in rows]
        rows = [(p, s) for p, s in rows if s]
        if not rows:
            continue
        out.append("### " + TITLES.get(fam, fam.replace("-", " ").title()))
        out.append("")
        out.append("<table>")
        for p, src in rows:
            out.append(
                '<tr><td><code>%s</code></td>'
                '<td><img src="%s" width="%d" alt="%s"></td>'
                '<td><code>%s</code></td></tr>'
                % (p["prop"], src, THUMB, p["prop"], esc(p["value"])))
            shown += 1
        out.append("</table>")
        out.append("")
    out.append("<!-- SHOWCASE:END -->")
    return "\n".join(out), shown


def main():
    picks = json.load(open(PICKS, encoding="utf-8"))
    block, shown = render(picks)
    text = open(README, encoding="utf-8").read()
    start, end = "<!-- SHOWCASE:START -->", "<!-- SHOWCASE:END -->"
    i, j = text.index(start), text.index(end) + len(end)
    open(README, "w", encoding="utf-8").write(text[:i] + block + text[j:])
    print("showcase: %d specimens across %d families -> README.md" %
          (shown, len({p["family"] for p in picks})))


if __name__ == "__main__":
    main()
