// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chrome-testing/proto/blueprint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateBlueprint_DemoType int32

const (
	TemplateBlueprint_BOX      TemplateBlueprint_DemoType = 0  // single div target
	TemplateBlueprint_TEXT     TemplateBlueprint_DemoType = 1  // paragraph of text as target
	TemplateBlueprint_FLEX     TemplateBlueprint_DemoType = 2  // flex container with child items
	TemplateBlueprint_GRID     TemplateBlueprint_DemoType = 3  // grid container with child items
	TemplateBlueprint_TABLE    TemplateBlueprint_DemoType = 4  // table element
	TemplateBlueprint_SVG      TemplateBlueprint_DemoType = 5  // SVG element with shapes
	TemplateBlueprint_POSITION TemplateBlueprint_DemoType = 6  // positioned element with siblings
	TemplateBlueprint_INLINE   TemplateBlueprint_DemoType = 7  // inline/span element within text flow
	TemplateBlueprint_MULTICOL TemplateBlueprint_DemoType = 8  // multi-column layout
	TemplateBlueprint_LIST     TemplateBlueprint_DemoType = 9  // list element (ul/ol)
	TemplateBlueprint_IMAGE    TemplateBlueprint_DemoType = 10 // img or element with background-image
	TemplateBlueprint_SCROLL   TemplateBlueprint_DemoType = 11 // scrollable container
)

// Enum value maps for TemplateBlueprint_DemoType.
var (
	TemplateBlueprint_DemoType_name = map[int32]string{
		0:  "BOX",
		1:  "TEXT",
		2:  "FLEX",
		3:  "GRID",
		4:  "TABLE",
		5:  "SVG",
		6:  "POSITION",
		7:  "INLINE",
		8:  "MULTICOL",
		9:  "LIST",
		10: "IMAGE",
		11: "SCROLL",
	}
	TemplateBlueprint_DemoType_value = map[string]int32{
		"BOX":      0,
		"TEXT":     1,
		"FLEX":     2,
		"GRID":     3,
		"TABLE":    4,
		"SVG":      5,
		"POSITION": 6,
		"INLINE":   7,
		"MULTICOL": 8,
		"LIST":     9,
		"IMAGE":    10,
		"SCROLL":   11,
	}
)

func (x TemplateBlueprint_DemoType) Enum() *TemplateBlueprint_DemoType {
	p := new(TemplateBlueprint_DemoType)
	*p = x
	return p
}

func (x TemplateBlueprint_DemoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateBlueprint_DemoType) Descriptor() protoreflect.EnumDescriptor {
	return file_chrome_testing_proto_blueprint_proto_enumTypes[0].Descriptor()
}

func (TemplateBlueprint_DemoType) Type() protoreflect.EnumType {
	return &file_chrome_testing_proto_blueprint_proto_enumTypes[0]
}

func (x TemplateBlueprint_DemoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateBlueprint_DemoType.Descriptor instead.
func (TemplateBlueprint_DemoType) EnumDescriptor() ([]byte, []int) {
	return file_chrome_testing_proto_blueprint_proto_rawDescGZIP(), []int{0, 0}
}

// TemplateBlueprint defines the demo shape for a single CSS property.
// The generator reads this + grammar values to produce the final HTML page.
type TemplateBlueprint struct {
	state    protoimpl.MessageState     `protogen:"open.v1"`
	DemoType TemplateBlueprint_DemoType `protobuf:"varint,1,opt,name=demo_type,json=demoType,proto3,enum=cssgen.TemplateBlueprint_DemoType" json:"demo_type,omitempty"`
	// Display title for the page, e.g. "Flex Direction"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// HTML tag for the demo target element (default: "div")
	TargetTag string `protobuf:"bytes,3,opt,name=target_tag,json=targetTag,proto3" json:"target_tag,omitempty"`
	// Inner HTML content of the target element
	TargetInnerHtml string `protobuf:"bytes,4,opt,name=target_inner_html,json=targetInnerHtml,proto3" json:"target_inner_html,omitempty"`
	// Base inline CSS on the target element, besides the property being tested.
	// e.g. "display: flex; gap: 8px; background: darkslategray;"
	TargetBaseStyle string `protobuf:"bytes,5,opt,name=target_base_style,json=targetBaseStyle,proto3" json:"target_base_style,omitempty"`
	// HTML for sibling elements rendered before the target
	SiblingsBefore []string `protobuf:"bytes,6,rep,name=siblings_before,json=siblingsBefore,proto3" json:"siblings_before,omitempty"`
	// HTML for sibling elements rendered after the target
	SiblingsAfter []string `protobuf:"bytes,7,rep,name=siblings_after,json=siblingsAfter,proto3" json:"siblings_after,omitempty"`
	// CSS applied to the .demo-area wrapper around the target
	WrapperStyle string `protobuf:"bytes,8,opt,name=wrapper_style,json=wrapperStyle,proto3" json:"wrapper_style,omitempty"`
	// HTML for child elements inside the target (used for flex/grid/position demos)
	ChildElements []string `protobuf:"bytes,9,rep,name=child_elements,json=childElements,proto3" json:"child_elements,omitempty"`
	// Maximum number of values to show (default: 36)
	MaxValues int32 `protobuf:"varint,10,opt,name=max_values,json=maxValues,proto3" json:"max_values,omitempty"`
	// Extra CSS rules to include in the <style> block (for .item, .flow-box, etc.)
	ExtraCss string `protobuf:"bytes,11,opt,name=extra_css,json=extraCss,proto3" json:"extra_css,omitempty"`
	// Name of the screenshot mode textproto template (e.g. "static", "temporal",
	// "scroll", "hover", "focus", "selection"). Maps to a file in
	// chrome-testing/screenshots/textproto/{name}.textproto.
	// Default: "static" (single screenshot).
	ScreenshotTextproto string `protobuf:"bytes,12,opt,name=screenshot_textproto,json=screenshotTextproto,proto3" json:"screenshot_textproto,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TemplateBlueprint) Reset() {
	*x = TemplateBlueprint{}
	mi := &file_chrome_testing_proto_blueprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBlueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBlueprint) ProtoMessage() {}

func (x *TemplateBlueprint) ProtoReflect() protoreflect.Message {
	mi := &file_chrome_testing_proto_blueprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBlueprint.ProtoReflect.Descriptor instead.
func (*TemplateBlueprint) Descriptor() ([]byte, []int) {
	return file_chrome_testing_proto_blueprint_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateBlueprint) GetDemoType() TemplateBlueprint_DemoType {
	if x != nil {
		return x.DemoType
	}
	return TemplateBlueprint_BOX
}

func (x *TemplateBlueprint) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TemplateBlueprint) GetTargetTag() string {
	if x != nil {
		return x.TargetTag
	}
	return ""
}

func (x *TemplateBlueprint) GetTargetInnerHtml() string {
	if x != nil {
		return x.TargetInnerHtml
	}
	return ""
}

func (x *TemplateBlueprint) GetTargetBaseStyle() string {
	if x != nil {
		return x.TargetBaseStyle
	}
	return ""
}

func (x *TemplateBlueprint) GetSiblingsBefore() []string {
	if x != nil {
		return x.SiblingsBefore
	}
	return nil
}

func (x *TemplateBlueprint) GetSiblingsAfter() []string {
	if x != nil {
		return x.SiblingsAfter
	}
	return nil
}

func (x *TemplateBlueprint) GetWrapperStyle() string {
	if x != nil {
		return x.WrapperStyle
	}
	return ""
}

func (x *TemplateBlueprint) GetChildElements() []string {
	if x != nil {
		return x.ChildElements
	}
	return nil
}

func (x *TemplateBlueprint) GetMaxValues() int32 {
	if x != nil {
		return x.MaxValues
	}
	return 0
}

func (x *TemplateBlueprint) GetExtraCss() string {
	if x != nil {
		return x.ExtraCss
	}
	return ""
}

func (x *TemplateBlueprint) GetScreenshotTextproto() string {
	if x != nil {
		return x.ScreenshotTextproto
	}
	return ""
}

var File_chrome_testing_proto_blueprint_proto protoreflect.FileDescriptor

const file_chrome_testing_proto_blueprint_proto_rawDesc = "" +
	"\n" +
	"$chrome-testing/proto/blueprint.proto\x12\x06cssgen\"\xfd\x04\n" +
	"\x11TemplateBlueprint\x12?\n" +
	"\tdemo_type\x18\x01 \x01(\x0e2\".cssgen.TemplateBlueprint.DemoTypeR\bdemoType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"target_tag\x18\x03 \x01(\tR\ttargetTag\x12*\n" +
	"\x11target_inner_html\x18\x04 \x01(\tR\x0ftargetInnerHtml\x12*\n" +
	"\x11target_base_style\x18\x05 \x01(\tR\x0ftargetBaseStyle\x12'\n" +
	"\x0fsiblings_before\x18\x06 \x03(\tR\x0esiblingsBefore\x12%\n" +
	"\x0esiblings_after\x18\a \x03(\tR\rsiblingsAfter\x12#\n" +
	"\rwrapper_style\x18\b \x01(\tR\fwrapperStyle\x12%\n" +
	"\x0echild_elements\x18\t \x03(\tR\rchildElements\x12\x1d\n" +
	"\n" +
	"max_values\x18\n" +
	" \x01(\x05R\tmaxValues\x12\x1b\n" +
	"\textra_css\x18\v \x01(\tR\bextraCss\x121\n" +
	"\x14screenshot_textproto\x18\f \x01(\tR\x13screenshotTextproto\"\x8e\x01\n" +
	"\bDemoType\x12\a\n" +
	"\x03BOX\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04FLEX\x10\x02\x12\b\n" +
	"\x04GRID\x10\x03\x12\t\n" +
	"\x05TABLE\x10\x04\x12\a\n" +
	"\x03SVG\x10\x05\x12\f\n" +
	"\bPOSITION\x10\x06\x12\n" +
	"\n" +
	"\x06INLINE\x10\a\x12\f\n" +
	"\bMULTICOL\x10\b\x12\b\n" +
	"\x04LIST\x10\t\x12\t\n" +
	"\x05IMAGE\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06SCROLL\x10\vB7Z5github.com/accretional/proto-css/chrome-testing/protob\x06proto3"

var (
	file_chrome_testing_proto_blueprint_proto_rawDescOnce sync.Once
	file_chrome_testing_proto_blueprint_proto_rawDescData []byte
)

func file_chrome_testing_proto_blueprint_proto_rawDescGZIP() []byte {
	file_chrome_testing_proto_blueprint_proto_rawDescOnce.Do(func() {
		file_chrome_testing_proto_blueprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chrome_testing_proto_blueprint_proto_rawDesc), len(file_chrome_testing_proto_blueprint_proto_rawDesc)))
	})
	return file_chrome_testing_proto_blueprint_proto_rawDescData
}

var file_chrome_testing_proto_blueprint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chrome_testing_proto_blueprint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chrome_testing_proto_blueprint_proto_goTypes = []any{
	(TemplateBlueprint_DemoType)(0), // 0: cssgen.TemplateBlueprint.DemoType
	(*TemplateBlueprint)(nil),       // 1: cssgen.TemplateBlueprint
}
var file_chrome_testing_proto_blueprint_proto_depIdxs = []int32{
	0, // 0: cssgen.TemplateBlueprint.demo_type:type_name -> cssgen.TemplateBlueprint.DemoType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chrome_testing_proto_blueprint_proto_init() }
func file_chrome_testing_proto_blueprint_proto_init() {
	if File_chrome_testing_proto_blueprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chrome_testing_proto_blueprint_proto_rawDesc), len(file_chrome_testing_proto_blueprint_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chrome_testing_proto_blueprint_proto_goTypes,
		DependencyIndexes: file_chrome_testing_proto_blueprint_proto_depIdxs,
		EnumInfos:         file_chrome_testing_proto_blueprint_proto_enumTypes,
		MessageInfos:      file_chrome_testing_proto_blueprint_proto_msgTypes,
	}.Build()
	File_chrome_testing_proto_blueprint_proto = out.File
	file_chrome_testing_proto_blueprint_proto_goTypes = nil
	file_chrome_testing_proto_blueprint_proto_depIdxs = nil
}
