// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chrome-testing/proto/propertydesc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExprType      string                 `protobuf:"bytes,1,opt,name=expr_type,json=exprType,proto3" json:"expr_type,omitempty"`     // e.g. "AccentColorExpr"
	DemoType      string                 `protobuf:"bytes,2,opt,name=demo_type,json=demoType,proto3" json:"demo_type,omitempty"`     // "box", "text", "flex", "grid", "margin"
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                       // extra CSS for the demo element, e.g. "background: cornflowerblue;"
	NumValues     int32                  `protobuf:"varint,4,opt,name=num_values,json=numValues,proto3" json:"num_values,omitempty"` // how many values to generate (default 8 if 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyDescriptor) Reset() {
	*x = PropertyDescriptor{}
	mi := &file_chrome_testing_proto_propertydesc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyDescriptor) ProtoMessage() {}

func (x *PropertyDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_chrome_testing_proto_propertydesc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyDescriptor.ProtoReflect.Descriptor instead.
func (*PropertyDescriptor) Descriptor() ([]byte, []int) {
	return file_chrome_testing_proto_propertydesc_proto_rawDescGZIP(), []int{0}
}

func (x *PropertyDescriptor) GetExprType() string {
	if x != nil {
		return x.ExprType
	}
	return ""
}

func (x *PropertyDescriptor) GetDemoType() string {
	if x != nil {
		return x.DemoType
	}
	return ""
}

func (x *PropertyDescriptor) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *PropertyDescriptor) GetNumValues() int32 {
	if x != nil {
		return x.NumValues
	}
	return 0
}

type PropertyDescriptors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*PropertyDescriptor  `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyDescriptors) Reset() {
	*x = PropertyDescriptors{}
	mi := &file_chrome_testing_proto_propertydesc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyDescriptors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyDescriptors) ProtoMessage() {}

func (x *PropertyDescriptors) ProtoReflect() protoreflect.Message {
	mi := &file_chrome_testing_proto_propertydesc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyDescriptors.ProtoReflect.Descriptor instead.
func (*PropertyDescriptors) Descriptor() ([]byte, []int) {
	return file_chrome_testing_proto_propertydesc_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyDescriptors) GetProperties() []*PropertyDescriptor {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_chrome_testing_proto_propertydesc_proto protoreflect.FileDescriptor

const file_chrome_testing_proto_propertydesc_proto_rawDesc = "" +
	"\n" +
	"'chrome-testing/proto/propertydesc.proto\x12\x06cssgen\"\x87\x01\n" +
	"\x12PropertyDescriptor\x12\x1b\n" +
	"\texpr_type\x18\x01 \x01(\tR\bexprType\x12\x1b\n" +
	"\tdemo_type\x18\x02 \x01(\tR\bdemoType\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"num_values\x18\x04 \x01(\x05R\tnumValues\"Q\n" +
	"\x13PropertyDescriptors\x12:\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x1a.cssgen.PropertyDescriptorR\n" +
	"propertiesB7Z5github.com/accretional/proto-css/chrome-testing/protob\x06proto3"

var (
	file_chrome_testing_proto_propertydesc_proto_rawDescOnce sync.Once
	file_chrome_testing_proto_propertydesc_proto_rawDescData []byte
)

func file_chrome_testing_proto_propertydesc_proto_rawDescGZIP() []byte {
	file_chrome_testing_proto_propertydesc_proto_rawDescOnce.Do(func() {
		file_chrome_testing_proto_propertydesc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chrome_testing_proto_propertydesc_proto_rawDesc), len(file_chrome_testing_proto_propertydesc_proto_rawDesc)))
	})
	return file_chrome_testing_proto_propertydesc_proto_rawDescData
}

var file_chrome_testing_proto_propertydesc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chrome_testing_proto_propertydesc_proto_goTypes = []any{
	(*PropertyDescriptor)(nil),  // 0: cssgen.PropertyDescriptor
	(*PropertyDescriptors)(nil), // 1: cssgen.PropertyDescriptors
}
var file_chrome_testing_proto_propertydesc_proto_depIdxs = []int32{
	0, // 0: cssgen.PropertyDescriptors.properties:type_name -> cssgen.PropertyDescriptor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chrome_testing_proto_propertydesc_proto_init() }
func file_chrome_testing_proto_propertydesc_proto_init() {
	if File_chrome_testing_proto_propertydesc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chrome_testing_proto_propertydesc_proto_rawDesc), len(file_chrome_testing_proto_propertydesc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chrome_testing_proto_propertydesc_proto_goTypes,
		DependencyIndexes: file_chrome_testing_proto_propertydesc_proto_depIdxs,
		MessageInfos:      file_chrome_testing_proto_propertydesc_proto_msgTypes,
	}.Build()
	File_chrome_testing_proto_propertydesc_proto = out.File
	file_chrome_testing_proto_propertydesc_proto_goTypes = nil
	file_chrome_testing_proto_propertydesc_proto_depIdxs = nil
}
