// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chrome-testing/proto/representative.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RepresentativeType defines a set of representative sample values for a
// grammar type that is recursive or open-ended (e.g. ColorType, LengthType).
// These short-circuit exhaustive enumeration to keep generation tractable.
type RepresentativeType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grammar rule name, e.g. "ColorType", "LengthType".
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// Hand-picked sample values that are visually distinct and meaningful.
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// CSS property names (kebab-case) for which this type IS the primary focus.
	// When generating values for a primary rule, the representative values are
	// skipped so the grammar is expanded fully — because the property exists
	// specifically to test this type.
	// e.g. ColorType has primary_rules: ["color", "background-color"]
	PrimaryRules  []string `protobuf:"bytes,3,rep,name=primary_rules,json=primaryRules,proto3" json:"primary_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepresentativeType) Reset() {
	*x = RepresentativeType{}
	mi := &file_chrome_testing_proto_representative_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepresentativeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepresentativeType) ProtoMessage() {}

func (x *RepresentativeType) ProtoReflect() protoreflect.Message {
	mi := &file_chrome_testing_proto_representative_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepresentativeType.ProtoReflect.Descriptor instead.
func (*RepresentativeType) Descriptor() ([]byte, []int) {
	return file_chrome_testing_proto_representative_proto_rawDescGZIP(), []int{0}
}

func (x *RepresentativeType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *RepresentativeType) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *RepresentativeType) GetPrimaryRules() []string {
	if x != nil {
		return x.PrimaryRules
	}
	return nil
}

// RepresentativeTypes is a top-level wrapper for a collection of representative types.
type RepresentativeTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*RepresentativeType  `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepresentativeTypes) Reset() {
	*x = RepresentativeTypes{}
	mi := &file_chrome_testing_proto_representative_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepresentativeTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepresentativeTypes) ProtoMessage() {}

func (x *RepresentativeTypes) ProtoReflect() protoreflect.Message {
	mi := &file_chrome_testing_proto_representative_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepresentativeTypes.ProtoReflect.Descriptor instead.
func (*RepresentativeTypes) Descriptor() ([]byte, []int) {
	return file_chrome_testing_proto_representative_proto_rawDescGZIP(), []int{1}
}

func (x *RepresentativeTypes) GetTypes() []*RepresentativeType {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_chrome_testing_proto_representative_proto protoreflect.FileDescriptor

const file_chrome_testing_proto_representative_proto_rawDesc = "" +
	"\n" +
	")chrome-testing/proto/representative.proto\x12\x06cssgen\"n\n" +
	"\x12RepresentativeType\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12#\n" +
	"\rprimary_rules\x18\x03 \x03(\tR\fprimaryRules\"G\n" +
	"\x13RepresentativeTypes\x120\n" +
	"\x05types\x18\x01 \x03(\v2\x1a.cssgen.RepresentativeTypeR\x05typesB7Z5github.com/accretional/proto-css/chrome-testing/protob\x06proto3"

var (
	file_chrome_testing_proto_representative_proto_rawDescOnce sync.Once
	file_chrome_testing_proto_representative_proto_rawDescData []byte
)

func file_chrome_testing_proto_representative_proto_rawDescGZIP() []byte {
	file_chrome_testing_proto_representative_proto_rawDescOnce.Do(func() {
		file_chrome_testing_proto_representative_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chrome_testing_proto_representative_proto_rawDesc), len(file_chrome_testing_proto_representative_proto_rawDesc)))
	})
	return file_chrome_testing_proto_representative_proto_rawDescData
}

var file_chrome_testing_proto_representative_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chrome_testing_proto_representative_proto_goTypes = []any{
	(*RepresentativeType)(nil),  // 0: cssgen.RepresentativeType
	(*RepresentativeTypes)(nil), // 1: cssgen.RepresentativeTypes
}
var file_chrome_testing_proto_representative_proto_depIdxs = []int32{
	0, // 0: cssgen.RepresentativeTypes.types:type_name -> cssgen.RepresentativeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chrome_testing_proto_representative_proto_init() }
func file_chrome_testing_proto_representative_proto_init() {
	if File_chrome_testing_proto_representative_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chrome_testing_proto_representative_proto_rawDesc), len(file_chrome_testing_proto_representative_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chrome_testing_proto_representative_proto_goTypes,
		DependencyIndexes: file_chrome_testing_proto_representative_proto_depIdxs,
		MessageInfos:      file_chrome_testing_proto_representative_proto_msgTypes,
	}.Build()
	File_chrome_testing_proto_representative_proto = out.File
	file_chrome_testing_proto_representative_proto_goTypes = nil
	file_chrome_testing_proto_representative_proto_depIdxs = nil
}
