// Code generated by genproto. DO NOT EDIT.

package csspb

// ScalarStopChars maps a scalarized leaf message's FQN to the printable
// ASCII characters its grammar rule can never contain. The parser cuts a
// scalar capture before the first such character — the lexical boundary
// that collapsing the rule to `string value = 1` erased.
var ScalarStopChars = map[string]string{
	".css.AngleType": " !\"#$%&'*/:;<=>?@[\\]^`{|}~",
	".css.CustomIdentType": " !\"#$%&'()*+,./:;<=>?@[\\]^`{|}~",
	".css.DashedIdentType": " !\"#$%&'()*+,./:;<=>?@[\\]^`{|}~",
	".css.Digit": " !\"#$%&'()*+,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".css.DimensionType": " !\"#$%&'()*,/:;<=>?@ABCDEFGIJKLMNOPRSTUVWXYZ[\\]^_`joy{|}~",
	".css.FlexType": " !\"$&'*/:;<=>?@[\\]^`{|}~",
	".css.FrequencyType": " !\"#$%&'()*,/:;<=>?@ABCDEFGIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijlmnopqrstuvwxy{|}~",
	".css.HexColorType": " !\"$%&'()*+,-./:;<=>?@GHIJKLMNOPQRSTUVWXYZ[\\]^_`ghijklmnopqrstuvwxyz{|}~",
	".css.IdentType": " !\"#$%&'()*+,./:;<=>?@[\\]^`{|}~",
	".css.IntegerType": " !\"#$%&'()*,./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".css.LengthType": " !\"#$%&'()*,/:;<=>?@ABCDEFGHIJKLMNOPRSTUVWXYZ[\\]^_`fgjkouyz{|}~",
	".css.NegativeIntegerType": " !\"#$%&'()*+,./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".css.NonNegativeFlexType": " !\"$&'*/:;<=>?@[\\]^`{|}~",
	".css.NonNegativeIntegerType": " !\"#$%&'*./:;<=>?@[\\]^`{|}~",
	".css.NonNegativeLengthType": " !\"#$%&'()*,/:;<=>?@ABCDEFGHIJKLMNOPRSTUVWXYZ[\\]^_`fgjkouyz{|}~",
	".css.NonNegativeNumberType": " !\"#$%&'*/:;<=>?@[\\]^`{|}~",
	".css.NonNegativePercentageType": " !\"#$&'*/:;<=>?@[\\]^`{|}~",
	".css.NonNegativeTimeType": " !\"#$%&'*/:;<=>?@[\\]^`{|}~",
	".css.NumberType": " !\"#$%&'()*,/:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklmnopqrstuvwxyz{|}~",
	".css.PercentageType": " !\"#$&'()*,/:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklmnopqrstuvwxyz{|}~",
	".css.PositiveIntegerType": " !\"#$%&'()*,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".css.ResolutionType": " !\"$&'*/:;<=>?@[\\]^`{|}~",
	".css.TimeType": " !\"#$%&'()*,/:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklnopqrtuvwxyz{|}~",
}
