// Code generated by genproto. DO NOT EDIT.

package csspb

// FieldSeparator maps a "parentFQN.fieldName" key to the literal that
// CollapseCommaList dropped when it rewrote "X (SEP X)*" into a repeated
// field. The renderer interleaves it between elements; the parser splits on it.
var FieldSeparator = map[string]string{
}
