combinator = child_combinator | column_combinator | descendant_combinator | next_sibling_combinator | subsequent_sibling_combinator ;

child_combinator = greater_than_sign_symbol ;

column_combinator = double_vertical_line_symbol ;

descendant_combinator = space_symbol ;

next_sibling_combinator = plus_sign_symbol ;

subsequent_sibling_combinator = tilde_symbol ;