combinator = child_combinator | column_combinator | descendant_combinator | next_sibling_combinator | subsequent_sibling_combinator ;

child_combinator = ">" ;

column_combinator = "||" ;

descendant_combinator = " " ;       (* It's actually a whitespace *)

next_sibling_combinator = "+" ;

subsequent_sibling_combinator = "~" ;