css_style_sheet = { at_rules | css_rule } ;      (* Empty stylesheet is valid CSS *)

css_rule = rule_definition , "{" , rule_properties , "}" ;

rule_definition = selector_chain , { "," , selector_chain } ;
selector_chain = rule_name , { combinator, rule_name } ;

rule_name = selector , { pseudo_operator }; 
pseudo_operator = (":", pseudo_class ) | ("::", pseudo_element ) ;

rule_properties = { property } ;      (* A rule might not have properties *)
