css_style_sheet = { at_rules | css_rule } ;      (* Empty stylesheet is valid CSS *)

css_rule = rule_definition , "{" , rule_properties , "}" ;

rule_definition = selector_chain , { "," , selector_chain } ;
selector_chain = rule_name , { combinator, rule_name } ;

rule_properties = { property } ;      (* A rule might not have properties *)

property =
    accent_color_expr | align_content_expr | align_items_expr
    | align_self_expr | alignment_baseline_expr | all_expr
    | anchor_name_expr | anchor_scope_expr | animation_composition_expr
    | animation_delay_expr | animation_direction_expr | animation_duration_expr
    | animation_fill_mode_expr | animation_iteration_count_expr | animation_name_expr
    | animation_play_state_expr | animation_range_end_expr | animation_range_start_expr
    | animation_range_expr | animation_timeline_expr | animation_timing_function_expr
    | animation_expr | appearance_expr | aspect_ratio_expr
    | backdrop_filter_expr | backface_visibility_expr | background_attachment_expr
    | background_blend_mode_expr | background_clip_expr | background_color_expr
    | background_image_expr | background_origin_expr | background_position_x_expr
    | background_position_y_expr | background_position_expr | background_repeat_expr
    | background_repeat_x_expr | background_repeat_y_expr | background_size_expr
    | background_expr | baseline_shift_expr | baseline_source_expr
    | block_size_expr | border_block_color_expr | border_block_end_color_expr
    | border_block_end_style_expr | border_block_end_width_expr | border_block_end_expr
    | border_block_start_color_expr | border_block_start_style_expr | border_block_start_width_expr
    | border_block_start_expr | border_block_style_expr | border_block_width_expr
    | border_block_expr | border_bottom_color_expr | border_bottom_left_radius_expr
    | border_bottom_right_radius_expr | border_bottom_style_expr | border_bottom_width_expr
    | border_bottom_expr | border_collapse_expr | border_color_expr
    | border_end_end_radius_expr | border_end_start_radius_expr | border_image_outset_expr
    | border_image_repeat_expr | border_image_slice_expr | border_image_source_expr
    | border_image_width_expr | border_image_expr | border_inline_color_expr
    | border_inline_end_color_expr | border_inline_end_style_expr | border_inline_end_width_expr
    | border_inline_end_expr | border_inline_start_color_expr | border_inline_start_style_expr
    | border_inline_start_width_expr | border_inline_start_expr | border_inline_style_expr
    | border_inline_width_expr | border_inline_expr | border_left_color_expr
    | border_left_style_expr | border_left_width_expr | border_left_expr
    | border_radius_expr | border_right_color_expr | border_right_style_expr
    | border_right_width_expr | border_right_expr | border_spacing_expr
    | border_start_end_radius_expr | border_start_start_radius_expr | border_style_expr
    | border_top_color_expr | border_top_left_radius_expr | border_top_right_radius_expr
    | border_top_style_expr | border_top_width_expr | border_top_expr
    | border_width_expr | border_expr | bottom_expr
    | box_align_expr | box_decoration_break_expr | box_direction_expr
    | box_flex_group_expr | box_flex_expr | box_lines_expr
    | box_ordinal_group_expr | box_orient_expr | box_pack_expr
    | box_shadow_expr | box_sizing_expr | break_after_expr
    | break_before_expr | break_inside_expr | caption_side_expr
    | caret_animation_expr | caret_color_expr | caret_shape_expr
    | caret_expr | clear_expr | clip_path_expr
    | clip_rule_expr | clip_expr | color_interpolation_filters_expr
    | color_interpolation_expr | color_scheme_expr | color_expr
    | column_count_expr | column_fill_expr | column_gap_expr
    | column_height_expr | column_rule_color_expr | column_rule_style_expr
    | column_rule_width_expr | column_rule_expr | column_span_expr
    | column_width_expr | column_wrap_expr | columns_expr
    | contain_intrinsic_block_size_expr | contain_intrinsic_height_expr | contain_intrinsic_inline_size_expr
    | contain_intrinsic_size_expr | contain_intrinsic_width_expr | contain_expr
    | container_name_expr | container_type_expr | container_expr
    | content_visibility_expr | content_expr | corner_block_end_shape_expr
    | corner_block_start_shape_expr | corner_bottom_left_shape_expr | corner_bottom_right_shape_expr
    | corner_bottom_shape_expr | corner_end_end_shape_expr | corner_end_start_shape_expr
    | corner_inline_end_shape_expr | corner_inline_start_shape_expr | corner_left_shape_expr
    | corner_right_shape_expr | corner_shape_expr | corner_start_end_shape_expr
    | corner_start_start_shape_expr | corner_top_left_shape_expr | corner_top_right_shape_expr
    | corner_top_shape_expr | counter_increment_expr | counter_reset_expr
    | counter_set_expr | cursor_expr | cx_expr
    | cy_expr | d_expr | direction_expr
    | display_expr | dominant_baseline_expr | dynamic_range_limit_expr
    | empty_cells_expr | field_sizing_expr | fill_opacity_expr
    | fill_rule_expr | fill_expr | filter_expr
    | flex_basis_expr | flex_direction_expr | flex_flow_expr
    | flex_grow_expr | flex_shrink_expr | flex_wrap_expr
    | flex_expr | float_expr | flood_color_expr
    | flood_opacity_expr | font_family_expr | font_feature_settings_expr
    | font_kerning_expr | font_language_override_expr | font_optical_sizing_expr
    | font_palette_expr | font_size_adjust_expr | font_size_expr
    | font_smooth_expr | font_stretch_expr | font_style_expr
    | font_synthesis_position_expr | font_synthesis_small_caps_expr | font_synthesis_style_expr
    | font_synthesis_weight_expr | font_synthesis_expr | font_variant_alternates_expr
    | font_variant_caps_expr | font_variant_east_asian_expr | font_variant_emoji_expr
    | font_variant_ligatures_expr | font_variant_numeric_expr | font_variant_position_expr
    | font_variant_expr | font_variation_settings_expr | font_weight_expr
    | font_width_expr | font_expr | forced_color_adjust_expr
    | gap_expr | grid_area_expr | grid_auto_columns_expr
    | grid_auto_flow_expr | grid_auto_rows_expr | grid_column_end_expr
    | grid_column_start_expr | grid_column_expr | grid_row_end_expr
    | grid_row_start_expr | grid_row_expr | grid_template_areas_expr
    | grid_template_columns_expr | grid_template_rows_expr | grid_template_expr
    | grid_expr | hanging_punctuation_expr | height_expr
    | hyphenate_character_expr | hyphenate_limit_chars_expr | hyphens_expr
    | image_orientation_expr | image_rendering_expr | image_resolution_expr
    | initial_letter_expr | inline_size_expr | inset_block_end_expr
    | inset_block_start_expr | inset_block_expr | inset_inline_end_expr
    | inset_inline_start_expr | inset_inline_expr | inset_expr
    | interactivity_expr | interest_delay_expr | interest_delay_end_expr
    | interest_delay_start_expr | interpolate_size_expr | isolation_expr
    | justify_content_expr | justify_items_expr | justify_self_expr
    | left_expr | letter_spacing_expr | lighting_color_expr
    | line_break_expr | line_clamp_expr | line_height_step_expr
    | line_height_expr | list_style_image_expr | list_style_position_expr
    | list_style_type_expr | list_style_expr | margin_block_end_expr
    | margin_block_start_expr | margin_block_expr | margin_bottom_expr
    | margin_inline_end_expr | margin_inline_start_expr | margin_inline_expr
    | margin_left_expr | margin_right_expr | margin_top_expr
    | margin_trim_expr | margin_expr | marker_end_expr
    | marker_mid_expr | marker_start_expr | marker_expr
    | mask_border_mode_expr | mask_border_outset_expr | mask_border_repeat_expr
    | mask_border_slice_expr | mask_border_source_expr | mask_border_width_expr
    | mask_border_expr | mask_clip_expr | mask_composite_expr
    | mask_image_expr | mask_mode_expr | mask_origin_expr
    | mask_position_expr | mask_repeat_expr | mask_size_expr
    | mask_type_expr | mask_expr | math_depth_expr
    | math_shift_expr | math_style_expr | max_block_size_expr
    | max_height_expr | max_inline_size_expr | max_width_expr
    | min_block_size_expr | min_height_expr | min_inline_size_expr
    | min_width_expr | mix_blend_mode_expr | object_fit_expr
    | object_position_expr | object_view_box_expr | offset_anchor_expr
    | offset_distance_expr | offset_path_expr | offset_position_expr
    | offset_rotate_expr | offset_expr | opacity_expr
    | order_expr | orphans_expr | outline_color_expr
    | outline_offset_expr | outline_style_expr | outline_width_expr
    | outline_expr | overflow_anchor_expr | overflow_block_expr
    | overflow_clip_margin_expr | overflow_inline_expr | overflow_wrap_expr
    | overflow_x_expr | overflow_y_expr | overflow_expr
    | overlay_expr | overscroll_behavior_block_expr | overscroll_behavior_inline_expr
    | overscroll_behavior_x_expr | overscroll_behavior_y_expr | overscroll_behavior_expr
    | padding_block_end_expr | padding_block_start_expr | padding_block_expr
    | padding_bottom_expr | padding_inline_end_expr | padding_inline_start_expr
    | padding_inline_expr | padding_left_expr | padding_right_expr
    | padding_top_expr | padding_expr | page_break_after_expr
    | page_break_before_expr | page_break_inside_expr | page_expr
    | paint_order_expr | perspective_origin_expr | perspective_expr
    | place_content_expr | place_items_expr | place_self_expr
    | pointer_events_expr | position_anchor_expr | position_area_expr
    | position_try_fallbacks_expr | position_try_order_expr | position_try_expr
    | position_visibility_expr | position_expr | print_color_adjust_expr
    | quotes_expr | r_expr | resize_expr
    | right_expr | rotate_expr | row_gap_expr
    | ruby_align_expr | ruby_overhang_expr | ruby_position_expr
    | rx_expr | ry_expr | scale_expr
    | scroll_behavior_expr | scroll_initial_target_expr | scroll_margin_block_end_expr
    | scroll_margin_block_start_expr | scroll_margin_block_expr | scroll_margin_bottom_expr
    | scroll_margin_inline_end_expr | scroll_margin_inline_start_expr | scroll_margin_inline_expr
    | scroll_margin_left_expr | scroll_margin_right_expr | scroll_margin_top_expr
    | scroll_margin_expr | scroll_marker_group_expr | scroll_padding_block_end_expr
    | scroll_padding_block_start_expr | scroll_padding_block_expr | scroll_padding_bottom_expr
    | scroll_padding_inline_end_expr | scroll_padding_inline_start_expr | scroll_padding_inline_expr
    | scroll_padding_left_expr | scroll_padding_right_expr | scroll_padding_top_expr
    | scroll_padding_expr | scroll_snap_align_expr | scroll_snap_stop_expr
    | scroll_snap_type_expr | scroll_target_group_expr | scroll_timeline_axis_expr
    | scroll_timeline_name_expr | scroll_timeline_expr | scrollbar_color_expr
    | scrollbar_gutter_expr | scrollbar_width_expr | shape_image_threshold_expr
    | shape_margin_expr | shape_outside_expr | shape_rendering_expr
    | speak_as_expr | stop_color_expr | stop_opacity_expr
    | stroke_dasharray_expr | stroke_dashoffset_expr | stroke_linecap_expr
    | stroke_linejoin_expr | stroke_miterlimit_expr | stroke_opacity_expr
    | stroke_width_expr | stroke_expr | tab_size_expr
    | table_layout_expr | text_align_last_expr | text_align_expr
    | text_anchor_expr | text_autospace_expr | text_box_edge_expr
    | text_box_trim_expr | text_box_expr | text_combine_upright_expr
    | text_decoration_color_expr | text_decoration_inset_expr | text_decoration_line_expr
    | text_decoration_skip_ink_expr | text_decoration_skip_expr | text_decoration_style_expr
    | text_decoration_thickness_expr | text_decoration_expr | text_emphasis_color_expr
    | text_emphasis_position_expr | text_emphasis_style_expr | text_emphasis_expr
    | text_indent_expr | text_justify_expr | text_orientation_expr
    | text_overflow_expr | text_rendering_expr | text_shadow_expr
    | text_size_adjust_expr | text_spacing_trim_expr | text_transform_expr
    | text_underline_offset_expr | text_underline_position_expr | text_wrap_mode_expr
    | text_wrap_style_expr | text_wrap_expr | timeline_scope_expr
    | top_expr | touch_action_expr | transform_box_expr
    | transform_origin_expr | transform_style_expr | transform_expr
    | transition_behavior_expr | transition_delay_expr | transition_duration_expr
    | transition_property_expr | transition_timing_function_expr | transition_expr
    | translate_expr | unicode_bidi_expr | user_modify_expr
    | user_select_expr | vector_effect_expr | vertical_align_expr
    | view_timeline_axis_expr | view_timeline_inset_expr | view_timeline_name_expr
    | view_timeline_expr | view_transition_class_expr | view_transition_name_expr
    | visibility_expr | white_space_collapse_expr | white_space_expr
    | widows_expr | width_expr | will_change_expr
    | word_break_expr | word_spacing_expr | writing_mode_expr
    | x_expr | y_expr | z_index_expr
    | zoom_expr ;      (* 523 properties *)