(* Empty stylesheet is valid CSS *)
css_style_sheet = { at_rule | css_rule } ;

css_rule = complex_selector_list , left_curly_bracket_symbol , rule_body , right_curly_bracket_symbol ;

(* A rule body can be empty, can have property or a nested rule *)
rule_body = { property | nested_css_rule | at_rule } ;

(* The nested rule is the same as a CSS rule, except the rule_name *)
(* can have an ampersand as a valid selector *)
nested_css_rule = nested_complex_selector_list , left_curly_bracket_symbol , rule_body , right_curly_bracket_symbol ;