demo_type: TEXT
title: "Font Width"
target_tag: "span"
target_base_style: "font-family: 'Inter', sans-serif; color: #fff; font-size: 26px; white-space: nowrap;"
target_inner_html: "Hamburgefonstiv"
max_values: 9
extra_css: "@import url('https://fonts.googleapis.com/css2?family=Inter:wdth@75..100');"
screenshot_textproto: "static"
