demo_type: TEXT
title: "Font Feature Settings"
target_base_style: "font-size: 28px; line-height: 1.6; font-family: 'EB Garamond', Georgia, serif;"
target_inner_html: "fi fl ffi Office 1/2 3/4 0123456789 SMALL CAPS"
extra_css: "@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800');"
max_values: 6
screenshot_textproto: "static"
