demo_type: TEXT
title: "Font Variation Settings"
target_tag: "span"
target_base_style: "font-family: 'Roboto Flex', sans-serif; color: #fff; font-size: 30px; white-space: nowrap;"
target_inner_html: "Default Text"
max_values: 10
extra_css: "@import url('https://fonts.googleapis.com/css2?family=Roboto+Flex:wght@100..1000&display=swap');"
screenshot_textproto: "static"
