demo_type: TEXT
title: "Font Style"
target_base_style: "font-size: 36px; line-height: 1.3;"
target_inner_html: "Hamburgefons"
extra_css: ".sample-small { font-size: 14px; color: #a0a0b0; line-height: 1.5; }"
screenshot_textproto: "static"
