demo_type: TEXT
title: "Font Size"
target_tag: "span"
target_base_style: "white-space: nowrap;"
target_inner_html: "The quick brown fox jumps over the lazy dog"
max_values: 15
extra_css: ".demo-text { color: #fff; white-space: nowrap; }"
screenshot_textproto: "static"
