demo_type: TEXT
title: "Font Synthesis Weight"
target_base_style: "font-family: 'Dancing Script', cursive; font-size: 32px; line-height: 1.5; font-weight: 900;"
target_inner_html: "The Quick Brown Fox jumps"
extra_css: "@import url('https://fonts.googleapis.com/css2?family=Dancing+Script');"
screenshot_textproto: "static"
