demo_type: TEXT
title: "Font Variation Settings"
target_tag: "span"
target_base_style: "color: #fff; font-size: 30px; white-space: nowrap;"
target_inner_html: "Default Text"
screenshot_textproto: "static"
