demo_type: TEXT
title: "Font Palette"
target_base_style: "font-family: 'Nabla', system-ui; font-size: 48px; line-height: 1.4;"
target_inner_html: "AaBbCc 123"
max_values: 4
extra_css: "@import url('https://fonts.googleapis.com/css2?family=Nabla&display=swap');"
screenshot_textproto: "static"
