demo_type: TEXT
title: "Font Variant Numeric"
target_base_style: "font-size: 32px; color: #fff; line-height: 1.5; font-family: Georgia, 'Times New Roman', serif;"
target_inner_html: "0123456789"
screenshot_textproto: "static"
