demo_type: TEXT
title: "Font Synthesis Small Caps"
target_base_style: "font-size: 28px; line-height: 1.5; font-variant: small-caps;"
target_inner_html: "The Quick Brown Fox"
screenshot_textproto: "static"
