demo_type: TEXT
title: "Font Variant Numeric"
target_base_style: "font-size: 32px; color: #fff; line-height: 1.5; font-family: Georgia, 'Times New Roman', serif;"
target_inner_html: "1/2 3/4 1st 2nd 0123456789"
max_values: 9
screenshot_textproto: "static"
