demo_type: TEXT
title: "Font Synthesis Position"
target_base_style: "font-family: 'Dancing Script', cursive; font-size: 36px; line-height: 1.8; font-variant-position: sub;"
target_inner_html: "H<sub>2</sub>O and E=mc<sup>2</sup>"
extra_css: "@import url('https://fonts.googleapis.com/css2?family=Dancing+Script');"
screenshot_textproto: "static"
