demo_type: BOX
title: "Timeline Scope"
target_base_style: "background: #0a0a1a; border-radius: 8px; padding: 16px; font-family: monospace; font-size: 12px; line-height: 1.7; color: #a5b4fc; min-height: 100px;"
target_inner_html: "<span style=\"color:#6b7280; font-style:italic;\">/* Extend a named timeline to an ancestor */</span><br><span style=\"color:#e94560;\">.ancestor</span> {<br>&nbsp;&nbsp;<span style=\"color:#34d399;\">timeline-scope</span>: <span style=\"color:#fbbf24;\">--my-scroll</span>;<br>&nbsp;&nbsp;<span style=\"color:#34d399;\">animation-timeline</span>: <span style=\"color:#fbbf24;\">--my-scroll</span>;<br>}<br><br><span style=\"color:#e94560;\">.descendant</span> {<br>&nbsp;&nbsp;<span style=\"color:#34d399;\">scroll-timeline-name</span>: <span style=\"color:#fbbf24;\">--my-scroll</span>;<br>}"
